version = 1

[include]
environments = [
  { remote = "zmitchell/rust-build" },
  { remote = "zmitchell/rust-dev" },
  { remote = "zmitchell/rust-test" },
]

[vars]
BIN_NAME = "ff"

[build.ffs]
command = '''
  mkdir -p $out/bin
  cargo build --release
  cp target/release/ff $out/bin/ff
'''
description = "A swiss-army knife for working on Flox"
version = "0.2.2"
runtime-packages = [ "libiconv" ]

[options]
cuda-detection = false
